drop table Person cascade constraints;
drop table "User" cascade constraints;
drop table Room cascade constraints;
drop table Reservation cascade constraints;
drop table Apartment cascade constraints;
drop table Regular cascade constraints;
drop table Service cascade constraints;
drop table Includes cascade constraints;
drop table ReservationService cascade constraints;

create table Person (
  PersonID number generated by default as identity primary key,
  Name varchar2(25) not null,
  Sex varchar2(6) check (Sex in ('Male', 'Female')),
  Address varchar2(50) not null,
  Mail varchar2(30) not null,
  Birth date not null
);

create table "User" (
  Login varchar2(8) not null,
  Authorization varchar2(8) check (Authorization in ('Employee', 'Admin', 'Manager'))not null,
  Info number not null, -- inherits? Person's info
  FOREIGN KEY (Info) REFERENCES Person(PersonID) on delete cascade
);

create table Service (
  ServiceID number generated by default as identity primary key,
  Name varchar2(25) not null,
  Price number(*,2) not null,
  Description varchar2(255)
);

create table Room (
  RoomNumber number generated by default as identity primary key,
  Floor number(1,0) not null,
  IsAvailable char check ( IsAvailable in ('Y', 'N')) not null,
  Price number(*,2) not null,
  Description varchar2(255)
);

create table Regular (
  Bed varchar2(7) check (Bed in ('Single', 'Double','2Single')) not null,
  RoomInfo number not null,
  FOREIGN KEY (RoomInfo) REFERENCES Room(RoomNumber)
);

create table Apartment (
  Room_quantity number not null,
  Capacity number not null,
  DoubleBed char check ( DoubleBed in ('Y', 'N')) not null,
  RoomInfo number not null,
  FOREIGN KEY (RoomInfo) REFERENCES Room(RoomNumber)
);

create table Reservation (
  ReservationID number generated by default as identity primary key,
  DateFrom date,
  DateTo date,
  Price number(*,2),
  Payment varchar2(7) check ( Payment in ('Card', 'Cash', 'Bitcoin')) not null,
  AppliesTo number not null,
  FOREIGN KEY (AppliesTo) REFERENCES Room(RoomNumber) on delete cascade
);

create table Includes (
    PRIMARY KEY (Reservation, Included),
    Reservation number not null,
    Included number not null,
    FOREIGN KEY (Reservation) REFERENCES Reservation(ReservationID) on delete cascade,
    FOREIGN KEY (Included) REFERENCES Person(PersonID) on delete cascade
);

create table ReservationService (
    PRIMARY KEY (Reservation, Service),
    Reservation number not null,
    Service number not null,
    FOREIGN KEY (Reservation) REFERENCES Reservation(ReservationID) on delete cascade,
    FOREIGN KEY (Service) REFERENCES Service(ServiceID) on delete cascade
);

insert into Room (Floor, IsAvailable, Price, Description) values ('1','Y','300.59','Ahoj Tomas');
insert into Room (Floor, IsAvailable, Price, Description) values ('2','N','0.257','Ahoj Matej');
insert into Room (Floor, IsAvailable, Price, Description) values ('3','Y','456789.00','Ahoj Timotej');


insert into Person (Name, Sex, Address, Mail, Birth) values ('Tomas', 'Male', 'Kocotomov 38', 'kocotom@gmail.com', date '1999-01-16');
insert into Person (Name, Sex, Address, Mail, Birth) values ('Andrej', 'Female', 'Na vyherni 38', 'gzvv@gmail.com', date '2002-07-20');
insert into Person (Name, Sex, Address, Mail, Birth) values ('Matej', 'Male', 'Trapakov 38', 'noname5749@gmail.com', date '2002-08-02');
insert into Person (Name, Sex, Address, Mail, Birth) values ('Timotej', 'Female', 'Madarsko 38', 'kdesiuz@gmail.com', date '2001-04-01');
insert into Person (Name, Sex, Address, Mail, Birth) values ('Samo', 'Male', 'Moravska 38', 'radpijuvodku@gmail.com', date '2001-11-16');


insert into "User" (Login, Authorization, Info) values ('xtrala14','Employee', '3');
insert into "User" (Login, Authorization, Info) values ('xadmin00','Admin', '4');


insert into Service (Name, Price, Description) values ('Snidane', '156.65', 'Hoste maji narok na snidani v nasi restauraci po predlozeni dukazu rezervace');
insert into Service (Name, Price, Description) values ('Uklid po vystehovani', '18832.00', 'Automaticka sluzba po vystehovani');


insert into Reservation (DateFrom, DateTo, Price, Payment, AppliesTo) values (date '2023-03-24', date '2023-03-27', '55.55', 'Bitcoin', '1');
insert into Reservation (DateFrom, DateTo, Price, Payment, AppliesTo) values (date '2023-03-28', date '2023-03-29', '66.55', 'Cash', '1');
insert into Reservation (DateFrom, DateTo, Price, Payment, AppliesTo) values (date '2023-03-24', date '2023-03-27', '77.55', 'Card', '2');


insert into Includes (Reservation, Included) values ('1', '1');
insert into Includes (Reservation, Included) values ('1', '2');
insert into Includes (Reservation, Included) values ('2', '3');

insert into ReservationService (Reservation, Service) values ('1', '2');
insert into ReservationService (Reservation, Service) values ('2', '1');


SELECT * FROM
Reservation, Person, Includes, ReservationService, Service
WHERE Reservation.ReservationID = Includes.Reservation AND Person.PersonID = Includes.Included AND ReservationService.Service = Service.ServiceID
ORDER BY Person.Name;