drop table Person cascade constraints;
drop table Employee cascade constraints;
drop table Room cascade constraints;
drop table Reservation cascade constraints;
drop table Apartment cascade constraints;
drop table Regular cascade constraints;
drop table Service cascade constraints;
drop table RoomService cascade constraints;
drop table ReservationPerson cascade constraints;
drop table ReservationService cascade constraints;

create table Person (
  PersonID number generated by default as identity primary key,
  Name varchar2(25) check (regexp_like(Name, '^[A-Z][a-z]+\ [A-Z][a-z]+$')) not null,
  Sex varchar2(6) check (Sex in ('Male', 'Female')),
  Address varchar2(100) not null,
  Mail varchar2(30) check (regexp_like(Mail, '^[a-zA-Z0-9_%*-+]+\@[a-z.]+\.[a-z]{2,3}$')),
  Birth date not null
);

-- Generalizace/specializace podle 3. pravidla v prezentaci
-- aby bylo mozne poslat PK toho kdo vytvoril rezervaci jako FK do rezervace
-- a zaroven PK vsech lidi, na ktere se rezervace vstahuje
create table Employee (
  PersonID number generated by default as identity primary key,
  Name varchar2(25) check (regexp_like(Name, '^[A-Z][a-z]+\ [A-Z][a-z]+$')) not null,
  Sex varchar2(6) check (Sex in ('Male', 'Female')),
  Address varchar2(100) not null,
  Mail varchar2(30) check (regexp_like(Mail, '^[a-zA-Z0-9_%*-+]+\@[a-z.]+\.[a-z]{2,3}$')),
  Birth date not null,
  Login varchar2(8) not null,
  Authorization varchar2(8) check (Authorization in ('Employee', 'Admin', 'Manager')) not null
);

create table Service (
  ServiceID number generated by default as identity primary key,
  Name varchar2(25) check (regexp_like(Name, '^[A-Z][a-z\ ]+$')) not null,
  Price number(*,2) not null,
  Description varchar2(255)
);

create table Room (
  RoomNumber number generated by default as identity primary key,
  Floor number(2,0) not null,
  IsAvailable char check ( IsAvailable in ('Y', 'N')) not null,
  Price number(*,2) not null,
  Description varchar2(255)
);

-- Generalizace/specializace podle 1. pravidla v prezentaci
-- protoze regular a apartment jsou pouze dodatecne informace o room entite
create table Regular (
  Bed varchar2(7) check (Bed in ('Single', 'Double','2Single')) not null,
  RoomInfo number not null,
  FOREIGN KEY (RoomInfo) REFERENCES Room(RoomNumber)
);

create table Apartment (
  Room_quantity number not null,
  Capacity number not null,
  DoubleBed char check ( DoubleBed in ('Y', 'N')) not null,
  Room number not null,
  FOREIGN KEY (Room) REFERENCES Room(RoomNumber)
);

create table Reservation (
  ReservationID number generated by default as identity primary key,
  DateFrom date,
  DateTo date,
  Price number(*,2),
  Payment varchar2(7) check ( Payment in ('Card', 'Cash', 'Bitcoin')) not null,
  RoomNumber number not null,
  MadeBy number not null,
  FOREIGN KEY (RoomNumber) REFERENCES Room(RoomNumber) on delete cascade,
  FOREIGN KEY (Madeby) REFERENCES Employee(PersonID) on delete cascade
);

create table RoomService (
    PRIMARY KEY (Room, Service),
    Room number not null,
    Service number not null,
    FOREIGN KEY (Room) REFERENCES Room(RoomNumber) on delete cascade,
    FOREIGN KEY (Service) REFERENCES Service(ServiceID) on delete cascade
);

create table ReservationPerson (
    PRIMARY KEY (Reservation, Person),
    Reservation number not null,
    Person number not null,
    FOREIGN KEY (Reservation) REFERENCES Reservation(ReservationID) on delete cascade,
    FOREIGN KEY (Person) REFERENCES Person(PersonID) on delete cascade
);

create table ReservationService (
    PRIMARY KEY (Reservation, Service),
    Reservation number not null,
    Service number not null,
    FOREIGN KEY (Reservation) REFERENCES Reservation(ReservationID) on delete cascade,
    FOREIGN KEY (Service) REFERENCES Service(ServiceID) on delete cascade
);

insert into Room (Floor, IsAvailable, Price, Description) values ('1','Y','300.59','Apartman pro rodiny');
insert into Room (Floor, IsAvailable, Price, Description) values ('2','N','250.257','Pokoj se dvema normalnimi postelemi');
insert into Room (Floor, IsAvailable, Price, Description) values ('3','Y','167.00','Pokoj s jednou spojenou posteli');
insert into Room (Floor, IsAvailable, Price, Description) values ('5','N','385.02','Pokoj, ktery jeste nebyl rezervovany');


insert into Apartment (Room_quantity, Capacity, DoubleBed, Room) values ('3', '5', 'Y', '1');
insert into Regular (Bed, RoomInfo) values ('2Single', '2');
insert into Regular (Bed, RoomInfo) values ('Double', '3');
insert into Regular (Bed, RoomInfo) values ('Double', '4');


insert into Person (Name, Sex, Address, Mail, Birth) values ('Tomas Novy', 'Male', 'Kocotomov 38', 'kocotom@gmail.com', date '1999-01-16');
insert into Person (Name, Sex, Address, Mail, Birth) values ('Andrej Nespor', 'Male', 'Na vyherni 38', 'xnespo10@stud.fit.vutbr.cz', date '2002-07-20');
insert into Person (Name, Sex, Address, Mail, Birth) values ('Matej Tomko', 'Male', 'Trapakov 38', 'xtomko07@fit.vutbr.cz', date '2002-08-02');
insert into Person (Name, Sex, Address, Mail, Birth) values ('Timotej Vesely', 'Male', 'Madarsko 38', 'veselyt@hotmail.com', date '2001-04-01');
insert into Person (Name, Sex, Address, Mail, Birth) values ('Adriana Nebeska', 'Female', 'Moravska 38', 'adrinka@seznam.cz', date '2001-11-16');


insert into Employee (Name, Sex, Address, Mail, Birth, Login, Authorization) values ('Josef Holy', 'Male', 'Pod mostem 69, Zlin', 'josefholy@gmial.com', date '1984-02-02', 'xholyz00', 'Employee');
insert into Employee (Name, Sex, Address, Mail, Birth, Login, Authorization) values ('Andrea Zelena', 'Female', 'Na vyhlidce 36, Brno', 'andreazelena@email.cz', date '1991-03-03', 'xzelen00','Admin');
insert into Employee (Name, Sex, Address, Mail, Birth, Login, Authorization) values ('Jan Modry', 'Male', 'Nad mostem 69, Ostrava', 'janmodry@gmial.com', date '1984-02-02', 'xmodry00', 'Employee');


insert into Service (Name, Price, Description) values ('Snidane', '156.65', 'Hoste maji narok na snidani v nasi restauraci po predlozeni dukazu rezervace');
insert into Service (Name, Price, Description) values ('Uklid po vystehovani', '18832.00', 'Automaticka sluzba po vystehovani');
insert into Service (Name, Price, Description) values ('Bezbarierovy pristup', '0', 'Pokoj s bezbarierovym pristupem');


insert into Reservation (DateFrom, DateTo, Price, Payment, RoomNumber, MadeBy) values (date '2023-03-24', date '2023-03-27', '55.55', 'Card', '1', '1');
insert into Reservation (DateFrom, DateTo, Price, Payment, RoomNumber, MadeBy) values (date '2023-03-28', date '2023-03-29', '66.55', 'Cash', '1', '1');
insert into Reservation (DateFrom, DateTo, Price, Payment, RoomNumber, MadeBy) values (date '2023-03-24', date '2023-03-27', '77.55', 'Bitcoin', '2', '1');
insert into Reservation (DateFrom, DateTo, Price, Payment, RoomNumber, MadeBy) values (date '2023-04-24', date '2023-05-27', '343.14', 'Bitcoin', '3', '3');


insert into RoomService (Room, Service) values ('1', '3');
insert into RoomService (Room, Service) values ('4', '3');

insert into ReservationPerson (Reservation, Person) values ('1', '1');
insert into ReservationPerson (Reservation, Person) values ('1', '2');
insert into ReservationPerson (Reservation, Person) values ('2', '3');
insert into ReservationPerson (Reservation, Person) values ('4', '2');

insert into ReservationService (Reservation, Service) values ('1', '2');
insert into ReservationService (Reservation, Service) values ('2', '1');

-- Pocet rezervaci podle zamestnance + maximalni a prumerna cena rezervace
-- 2 tables
-- Number of res by employee + max, avg price
SELECT e.Name, e.Login as Employee_Name, COUNT(r.ReservationID) as Number_of_Reservations, MAX(r.Price) as Max_Price, AVG(r.Price) as Average_Price
FROM Employee e
JOIN Reservation r ON e.PersonID = r.MadeBy
GROUP BY e.Name, e.Login;

-- Jmena vsech lidi v systemu a pocet jejich rezervaci (vcetne zamestnancu)
-- 2 tables
-- All people registered and their ResCount
SELECT p.Name, count(r.ReservationID) AS ReservationCount
FROM Person p
LEFT JOIN Reservation r ON p.PersonID = r.MadeBy
GROUP BY p.Name
ORDER BY ReservationCount DESC;

-- Vsechny nekdy rezervovane mistnosti
-- 3 tables
-- Ever reserved rooms with service #3
SELECT r.*
FROM Room r
JOIN RoomService rs ON r.RoomNumber = rs.Room
JOIN Service s ON rs.Service = s.ServiceID
WHERE s.ServiceID = 3
AND r.RoomNumber IN (
  SELECT DISTINCT RoomNumber
  FROM Reservation
);

-- Rezervace a vydelek za posledni rok podle typu platby
-- Agg. func + group by
-- Reservations last year
SELECT Payment, COUNT(*) AS NumberOfReservations, SUM(res.Price) AS TotalRevenue
FROM Reservation res
WHERE res.DateFrom >= TRUNC(SYSDATE, 'YEAR')
GROUP BY Payment;

-- Prumerna cena pokoju pro kazde patro
-- Agg. func + group by
-- Avg price each floor
SELECT Floor, AVG(Price) AS AvgPrice
FROM Room
GROUP BY Floor;

-- Vsechny pokoje, ktere byly nekdy rezervovany
-- EXISTS predicate
-- Rooms ever reserved
SELECT * FROM Room r
WHERE EXISTS (
  SELECT * FROM Reservation res
  WHERE res.RoomNumber = r.RoomNumber
)
ORDER BY RoomNumber;

-- Pokoje typu regular, ktere maji typ postele double
-- IN predicate
-- Regular rooms with double beds
SELECT *
FROM Room
WHERE Room.RoomNumber IN (
  SELECT RoomInfo
  FROM Regular
  WHERE Bed = 'Double'
);


